-- Migration for DSA Architecture (SkillBridge Pro)

-- 1. Career Readiness Score
CREATE TABLE public.career_readiness_snapshots (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    total_score INT NOT NULL CHECK (total_score BETWEEN 0 AND 100),
    tech_score INT NOT NULL,
    project_score INT NOT NULL,
    journey_score INT NOT NULL,
    streak_score INT NOT NULL,
    evidence_score INT NOT NULL,
    calculated_at TIMESTAMPTZ DEFAULT NOW(),
    trigger_event VARCHAR(50)
);

CREATE INDEX idx_readiness_user_date ON public.career_readiness_snapshots(user_id, calculated_at DESC);

ALTER TABLE public.career_readiness_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own snapshots" ON public.career_readiness_snapshots FOR SELECT USING (auth.uid() = user_id);
-- Snapshots are only generated by the backend (Edge Functions/admin role) so no insert/update policies for learners.

-- 2. XP, Levels, and Streaks (Gamification)
CREATE TABLE public.xp_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    reference_id UUID,
    xp_awarded INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, event_type, reference_id) 
);

CREATE TABLE public.user_gamification_stats (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    total_xp INT DEFAULT 0,
    current_level INT DEFAULT 1,
    current_streak INT DEFAULT 0,
    last_active_date DATE
);

-- RLS for Gamification tables
ALTER TABLE public.xp_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_gamification_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own xp events" ON public.xp_events FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own gamification stats" ON public.user_gamification_stats FOR SELECT USING (auth.uid() = user_id);

-- Backend RPC to safely grant XP and calculate level
CREATE OR REPLACE FUNCTION public.grant_xp(p_user_id UUID, p_event VARCHAR, p_ref_id UUID, p_xp INT)
RETURNS void AS $$
BEGIN
    INSERT INTO public.xp_events (user_id, event_type, reference_id, xp_awarded)
    VALUES (p_user_id, p_event, p_ref_id, p_xp);
    
    INSERT INTO public.user_gamification_stats (user_id, total_xp, current_level)
    VALUES (p_user_id, p_xp, floor(sqrt(p_xp / 100.0)) + 1)
    ON CONFLICT (user_id) DO UPDATE 
    SET total_xp = public.user_gamification_stats.total_xp + EXCLUDED.total_xp,
        current_level = floor(sqrt((public.user_gamification_stats.total_xp + EXCLUDED.total_xp) / 100.0)) + 1;
EXCEPTION WHEN unique_violation THEN
    -- Silently ignore duplicate XP grants for the same event
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Portfolio Verification State Machine & Auditing
CREATE TABLE public.portfolio_submissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    github_url TEXT,
    demo_url TEXT,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'ai_check_queued', 'ai_check_running', 'ai_check_passed', 'needs_changes', 'human_review_queued', 'human_reviewed', 'verified', 'rejected')),
    submission_version INT DEFAULT 1,
    ai_bypassed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.verification_audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    portfolio_id UUID REFERENCES public.portfolio_submissions(id) ON DELETE CASCADE,
    old_state TEXT,
    new_state TEXT NOT NULL,
    actor_id UUID REFERENCES public.users(id),
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.portfolio_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own portfolios" ON public.portfolio_submissions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own portfolios" ON public.portfolio_submissions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own draft portfolios" ON public.portfolio_submissions FOR UPDATE USING (auth.uid() = user_id AND status = 'draft');

CREATE POLICY "Users can view own verification logs" ON public.verification_audit_logs FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.portfolio_submissions WHERE id = portfolio_id AND user_id = auth.uid())
);

-- Trigger to auto-log state transitions
CREATE OR REPLACE FUNCTION log_portfolio_state_transition()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO public.verification_audit_logs (portfolio_id, old_state, new_state, actor_id)
        VALUES (NEW.id, OLD.status, NEW.status, auth.uid());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trigger_portfolio_state_transition
    AFTER UPDATE ON public.portfolio_submissions
    FOR EACH ROW
    EXECUTE FUNCTION log_portfolio_state_transition();

-- 4. Mentor Matching Materialized View
-- Assumes mentors_profile already exists from Phase 4
-- We will add expertise tags to it if not present
ALTER TABLE public.mentors_profile ADD COLUMN IF NOT EXISTS expertise_tags TEXT[] DEFAULT '{}';
ALTER TABLE public.mentors_profile ADD COLUMN IF NOT EXISTS hourly_rate NUMERIC(10,2) DEFAULT 0.0;
ALTER TABLE public.mentors_profile ADD COLUMN IF NOT EXISTS total_sessions INT DEFAULT 0;

CREATE MATERIALIZED VIEW public.active_mentors_mv AS
SELECT 
    m.id,
    u.full_name,
    m.quality_score AS rating,
    m.expertise_tags,
    m.hourly_rate,
    m.total_sessions,
    (m.availability IS NOT NULL AND jsonb_array_length(m.availability) > 0) AS has_availability,
    CASE WHEN m.total_sessions < 5 THEN 1.0 ELSE 0.0 END AS cold_start_boost
FROM public.mentors_profile m
JOIN public.users u ON m.id = u.id
WHERE m.verification_status = 'verified' AND m.payout_status = 'active';

CREATE UNIQUE INDEX idx_active_mentors_mv_id ON public.active_mentors_mv(id);
CREATE INDEX idx_active_mentors_mv_tags ON public.active_mentors_mv USING GIN (expertise_tags);
CREATE INDEX idx_active_mentors_mv_rate ON public.active_mentors_mv(hourly_rate);
